title: Oluwatobi Akinwamide
logo: IMG_34844.PNG
description: With 2 years of experience, I excel at transforming complex data into actionable insights. Proficient in SQL, Excel, and data visualization tools like Tableau and Power BI,I have a proven track record of identifying trends and driving data-driven decisions I excel at identifying trends, uncovering patterns, and driving data-driven decision-making.My experience spans across various industries, where I have successfully collaborated with cross-functional teamsto optimize processes, enhance customer experiences, and boost business performance.I am passionate about leveraging data to solve real-world problems and continuouslystrive to improve my analytical skills to deliver impactful results.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
