title: Oluwatobi Akinwamide
logo: toby.jpeg
description: With about 2 years of experience in data analysis, I excel in working with diverse data sources and transforming complex datasets into actionable insights that support informed decision-making.  I am proficient in statistical analysis, data mining, and visualization techniques, which allow me to uncover valuable insights and identify trends. I am adept with statistical and data analytics tools such as Python, Machine Learning, Excel, SQL, and Power BI. Specializing in leveraging data insights for business decisions, I am also proficient in Microsoft Office and data manipulation, which enhances my ability to provide valuable analytical solutions.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
